### ISSUE TITLE
Error: No connection! -- Getting when trying run .discover()

### ISSUE THREAD

**Issue by JabariD** [haf-decent/arpping#16]
How do I establish an active internet/interface connection?

I understand that the documentation reads:
Any methods that depend on ping/arp (and therefore an active internet/interface connection) will throw an error if no connection is available.

Here's my code:
![image](https://user-images.githubusercontent.com/52969350/151680369-d7e5c1c8-3d0a-42d1-9add-784dc5238705.png)

**Fantastic NPM Package!**

**Comment by haf-decent** [comment]
In your `options` object, the top-level `interface` key should be `interfaceFilters`. I guess I could probably add a console.warn for invalid options if the `debug` flag is set, but, for now, let me know if that fixes your issue. Also thanks, glad it's helpful!

**Comment by JabariD** [comment]
Perfect that fixed the error!

Now I'm getting the following:
Error: Invalid mask for ip4: ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff
    at netmask.js:88:15)


Here's my code:
![image](https://user-images.githubusercontent.com/52969350/151680970-de9afc83-f6d5-4340-8bf2-569efc70973c.png)

**Comment by haf-decent** [comment]
Hmm, when I run your code on my machine, I connect to the `lo0` interface, which ends up not returning any results because it's the [loopback interface](https://askubuntu.com/questions/247625/what-is-the-loopback-device-and-how-do-i-use-it). I think this is because your code removes the `internal: [false]` requirement. I probably shouldn't have even included that filter, as I don't think there's any situation in which you'd want an internal network. Just to be sure, because I'm not getting the same error, could you let me know what network interface you're connecting to?

So, for how to fix your error, I would suggest removing the `internal` key completely (and probably `family` as well just to be safe). That seems to fix the issue on my machine.

**Comment by JabariD** [comment]
Ah that fixed it! Everything is working as expected! Thanks!
